name: auth_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  sqflite_common_ffi: ^2.0.0+1


flutter:
  uses-material-design: true
